// Generated by CoffeeScript 1.6.3
var PivotItem;

PivotItem = (function() {
  PivotItem.prototype.event = null;

  PivotItem.prototype.funk = null;

  PivotItem.prototype.value = null;

  PivotItem.prototype.once = false;

  function PivotItem(parent) {
    this.parent = parent;
  }

  PivotItem.prototype.trigger = function(value) {
    this.set(value);
    if (typeof this.funk === "function") {
      this.funk(value);
    }
    if (this.once) {
      this.off();
    }
    return this;
  };

  PivotItem.prototype.set = function(value) {
    if (value === this.value) {
      return;
    }
    this.parent.set(this.event, value);
    return this.value = value;
  };

  PivotItem.prototype.get = function() {
    return this.value;
  };

  PivotItem.prototype.off = function() {
    return this.parent.off(this.event, this.funk);
  };

  PivotItem.prototype.on = function() {
    return this.parent.on(this.event, this.funk);
  };

  return PivotItem;

})();

if (exports && module && module.exports) {
  module.exports = PivotItem;
} else if (define && define.amd) {
  define(function() {
    return PivotItem;
  });
}
